# Site settings
title: Paramdigma
email: info@paramdigma.com
description: >- # this means to ignore newlines until "baseurl:"
  Computational Knowledge Collective
logo: /assets/img/Logo.svg

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://paramdigma.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paramdigma
github_username: paramdigma
facebook_username: paramdigma
instagram_username: paramdigma
vimeo_username: paramdigma

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
plugins:
  - jekyll-feed

paginate_path: '/blog/page:num/'
paginate: 5

collections:
  pages:
    output: true
    permalink: /:title/index.html
  categories:
    output: true
    permalink: /categories/:title/index.html
  projects:
    output: true
    permalink: /projects/:title/index.html
  tutorials:
    output: true
    permalink: /tutorials/:title/index.html
