# Site settings
title: Paramdigma
email: info@paramdigma.com
description: >- # this means to ignore newlines until "baseurl:"
  Computational Knowledge Collective
logo: /assets/img/Logo.svg

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://paramdigma.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paramdigma
github_username: paramdigma
facebook_username: paramdigma
instagram_username: paramdigma
vimeo_username: paramdigma

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
plugins:
  - jekyll-feed

paginate_path: '/blog/page:num/'
paginate: 5
permalink: blog/:year-:month-:title.html

webrick:
  headers:
    Access-Control-Allow-Origin: '*'

collections:
  pages:
    output: true
    permalink: /:title/
  categories:
    output: true
    permalink: /categories/:title/
  projects:
    output: true
    permalink: /projects/:title/
  tutorials:
    output: true
    permalink: /tutorials/:title/

defaults:
  - scope:
      path: '' # All pages and posts
    values:
      layout: null
  - scope:
      path: '' # All pages and posts
      type: 'posts'
    values:
      layout: 'post-sidebar'
      hero:
        particles: true
        color: info
        size: medium
  - scope:
      path: '' # All pages and posts
      type: 'pages'
    values:
      layout: 'page'
      hero:
        particles: true
        color: primary
        size: medium
  - scope:
      path: '' # All pages and posts
      type: 'tutorials'
    values:
      layout: 'page'
      hero:
        particles: true
        color: success
        size: medium
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'page'
      hero:
        particles: true
        color: success
        size: medium
